# useful commands:
# docker-compose up
# docker-compose ps
# docker inspect <container>

# start a new installation, all previous data will be lost
# docker-compose down
# docker-compose build   # when the code has changed
# docker volume ls # should report otobo_mariadb_data and otobo_opt_otobo
# docker volume rm otobo_mariadb_data otobo_opt_otobo
# docker volume ls # should show no otobo volumes

# most current docker-compose file version, as of 2020-05-21
version: '3.3'

services:

  # the database
  db:
    image: mariadb:10.5.3-bionic
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

    # Expose the mysql default port to the host
    ports:
      - "3306:3306"

    # Set the db root passward
    # the database 'otobo' and the db user 'otobo' are created by installer.pl
    environment:
      MYSQL_ROOT_PASSWORD: otobo_root_db_passwd
      #MYSQL_DATABASE: otobo
      #MYSQL_USER: otobo
      #MYSQL_PASSWORD: otobo

    command: --max_allowed_packet=68157440 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-log-file-size=268435456

  web:
    # use ./Dockerfile for building, image otobo-web
    build:
      context: .
    depends_on:
      - db
    restart: always
    # Expose the Plack default port to the host
    ports:
      - "5000:5000"
    volumes:
      - opt_otobo:/opt/otobo

# no volumnes need to be exposed across services
volumes:
  mariadb_data: {}
  opt_otobo: {}
