# Docker compose file for OTOBO webserver and database.
# See also DOCKER.md.

# most current docker-compose file version, as of 2020-05-21
version: '3.3'

services:

  # the database
  db:
    image: mariadb:10.5.3-bionic
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

    # do not expose the mysql default port to the docker host host
    # use 'docker exec -it otobo_db_1 mysql ...' when access is needed
    # because the the otobo DB user is allowed for the complete Docker network
    # ports:
      #- "5001:3306"

    # Set the db root password
    # the database 'otobo' and the db user 'otobo' are created by installer.pl
    environment:
      MYSQL_ROOT_PASSWORD: otobo_root_db_passwd
      #MYSQL_DATABASE: otobo
      #MYSQL_USER: otobo
      #MYSQL_PASSWORD: otobo

    command: --max_allowed_packet=68157440 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-log-file-size=268435456

  web:
    # use ./Dockerfile for building, image otobo-web
    build:
      context: .
    # give a name to the build image so that the service 'cron' can reuse it
    image: otobo_web:latest
    depends_on:
      - db
    restart: always
    # Expose the Plack default port to the host
    ports:
      - "5000:5000"
    volumes:
      - opt_otobo:/opt/otobo
    command: web

  cron:
    image: otobo_web:latest
    volumes:
      - opt_otobo:/opt/otobo
    command: cron

# no volumnes need to be exposed across services
volumes:
  mariadb_data: {}
  opt_otobo: {}
