%YAML 1.1
---
# just like syntax_check.yml, only using a different check
name: 'CodePolicy'
on: ['pull_request']
#on: ['push', 'pull_request']
jobs:
    CodePolicy:
        runs-on: 'ubuntu-latest'
        env:
            PERL5LIB: local/lib/perl5
        steps:
            - id: files
              uses: jitterbit/get-changed-files@v1

            - name: 'install dependencies'
              run: sudo apt install -y libcode-tidyall-perl libxml2-utils libxml-libxslt-perl cpanminus

            - name: 'checkout otobo'
              uses: actions/checkout@v2

            # some diagnostics
            - name: diagnostics
              run: |
                perl -v
                printenv | sort

            # Use caching for not needing to reinstall modules from CPAN for every check.
            # Packages are reinstalled when cpanfile.docker changes or when
            # cache key is manually changed.
            # Set current date for forcing a rebuild. In this case, make sure that
            # code_policy.yml and syntax_check.yml are kept in sync.
            # The rules where the cache is visible are not obvious.
            # See https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
            - name: 'check cache for CPAN modules'
              uses: actions/cache@v2
              id: local_lib
              with:
                path: local
                key: ${{ runner.os }}-${{ hashFiles('cpanfile.docker') }}-local_lib-20210923j

            - name: 'install from cpanfile.docker'
              if: steps.local_lib.outputs.cache-hit != 'true'
              run: |
                cpanm -l local --quiet --notest --installdeps --cpanfile cpanfile.docker . || sh -xc 'cat ~/.cpanm/work/*/build.log'

            - name: 'checkout codepolicy'
              uses: actions/checkout@v2
              with:
                repository: RotherOSS/codepolicy
                ref: rel-10_0_4
                path: codepolicy

            - name: 'run CodePolicy'
              run: codepolicy/bin/otobo.CodePolicy.pl -l ${{ steps.files.outputs.added_modified }}
