%YAML 1.1
---
name: 'CodePolicy'
#on: ['pull_request']
on: ['push']
jobs:
    CodePolicy:
        runs-on: 'ubuntu-latest'
        env:
            PERL5LIB: local
        steps:
            - id: files
              uses: jitterbit/get-changed-files@v1

            - name: 'install dependencies'
              run: sudo apt install -y libxml2-utils libxml-libxslt-perl cpanminus

            - name: 'checkout otobo'
              uses: actions/checkout@v2

            # some diagnostics
            - name: diagnostics
              run: |
                unname -a
                perl -V
                printenv | sort

            # no need to reinstall modules from CPAN for every check, cache them
            # Packages are reinstalled when cpanfile.docker changes.
            # Set current date for forcing a rebuild.
            - name: 'check cache for CPAN modules'
              uses: actions/cache@v2
              id: local_lib
              with:
                path: local
                key: ${{ runner.os }}-${{ hashFiles('cpanfile.docker') }}-local_lib-20210923a

            - name: 'install from cpanfile.docker'
              if: steps.local_lib.outputs.cache-hit != 'true'
              run: |
                cpanm -l local --quiet --notest Code::TidyAll
                cpanm -l local --quiet --notest XML::LibXSLT
                cpanm -l local --quiet --notest --installdeps --cpanfile cpanfile.docker . || sh -xc 'cat ~/.cpanm/work/*/build.log'

            - name: 'tree local'
              run: tree local

            - name: 'checkout codepolicy'
              uses: actions/checkout@v2
              with:
                repository: RotherOSS/codepolicy
                ref: rel-10_0_4
                path: codepolicy

            - name: 'run CodePolicy'
              run: codepolicy/bin/otobo.CodePolicy.pl -l ${{ steps.files.outputs.added_modified }}
