# adapted from https://raku-advent.blog/2019/12/06/put-some-github-actions-in-your-raku-repositories/
name: "Happy Stanislaus day"
on: [push]

jobs:
  seasonal_greetings:
    runs-on: ubuntu-latest
    steps:
      - name: All the best Stanislaus!
        run: echo Merry name day, Stanislaus!
